# Generated by Django 4.2.30 on 2026-07-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='订单ID')),
                ('cl_ord_id', models.CharField(blank=True, max_length=64, verbose_name='客户自定义订单ID')),
                ('inst_id', models.CharField(db_index=True, max_length=50, verbose_name='产品ID')),
                ('td_mode', models.CharField(default='cash', max_length=20, verbose_name='交易模式')),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='买卖方向')),
                ('ord_type', models.CharField(choices=[('market', '市价单'), ('limit', '限价单'), ('post_only', '只做maker'), ('fok', '全部成交或立即取消'), ('ioc', '立即成交并取消剩余')], max_length=20, verbose_name='订单类型')),
                ('sz', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='委托数量')),
                ('px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='委托价格')),
                ('fill_sz', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='成交数量')),
                ('fill_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='成交均价')),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='手续费')),
                ('fee_ccy', models.CharField(blank=True, max_length=20, verbose_name='手续费币种')),
                ('state', models.CharField(choices=[('live', '等待成交'), ('partially_filled', '部分成交'), ('filled', '完全成交'), ('canceled', '已撤销'), ('failed', '失败')], default='live', max_length=20, verbose_name='订单状态')),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='盈亏(平仓时)')),
                ('source', models.CharField(default='manual', help_text='来源: manual / strategy / signal', max_length=50, verbose_name='来源')),
                ('strategy_id', models.IntegerField(blank=True, null=True, verbose_name='关联策略ID')),
                ('signal_id', models.IntegerField(blank=True, null=True, verbose_name='关联信号ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'db_table': 'trade_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inst_id', 'state'], name='trade_order_inst_id_0f9179_idx'), models.Index(fields=['created_at'], name='trade_order_created_6784be_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建'), ('submitted', '已提交'), ('filled', '成交'), ('partial_fill', '部分成交'), ('canceled', '撤销'), ('amended', '修改'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='操作类型')),
                ('detail', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.tradeorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单日志',
                'verbose_name_plural': '订单日志',
                'db_table': 'trade_order_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
