# Generated by Django 4.2.30 on 2026-08-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_tradeorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('inst_id', models.CharField(blank=True, help_text='留空则适用任意品种', max_length=50, verbose_name='产品ID')),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], default='buy', max_length=10, verbose_name='买卖方向')),
                ('ord_type', models.CharField(default='market', max_length=20, verbose_name='订单类型')),
                ('sz', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='委托数量')),
                ('px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='委托价格')),
                ('td_mode', models.CharField(default='cash', max_length=20, verbose_name='交易模式')),
                ('trigger_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='触发价')),
                ('tp_trigger_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='止盈触发价')),
                ('sl_trigger_px', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='止损触发价')),
                ('algo_type', models.CharField(blank=True, help_text='twap=时间加权 / iceberg=冰山', max_length=20, verbose_name='算法类型')),
                ('total_sz', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='算法总数量')),
                ('slices', models.IntegerField(blank=True, help_text='TWAP/冰山拆分的子单数量', null=True, verbose_name='切片数量')),
                ('interval', models.IntegerField(blank=True, null=True, verbose_name='间隔秒数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_templates', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单模板',
                'verbose_name_plural': '订单模板',
                'db_table': 'trade_order_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
