# Generated by Django 4.2.30 on 2026-07-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='交易品种ID')),
                ('inst_type', models.CharField(choices=[('SPOT', '现货'), ('MARGIN', '杠杆'), ('SWAP', '永续合约'), ('FUTURES', '交割合约'), ('OPTION', '期权')], max_length=20, verbose_name='产品类型')),
                ('uly', models.CharField(default='', max_length=50, verbose_name='标的指数')),
                ('base_ccy', models.CharField(default='', max_length=20, verbose_name='基础币种')),
                ('quote_ccy', models.CharField(default='', max_length=20, verbose_name='计价币种')),
                ('ct_val', models.CharField(default='', max_length=50, verbose_name='合约面值')),
                ('ct_mult', models.CharField(default='', max_length=50, verbose_name='合约乘数')),
                ('lot_sz', models.CharField(default='', max_length=50, verbose_name='最小下单数量')),
                ('min_sz', models.CharField(default='', max_length=50, verbose_name='最小下单数量')),
                ('tick_sz', models.CharField(default='', max_length=50, verbose_name='价格精度')),
                ('state', models.CharField(default='live', max_length=20, verbose_name='产品状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易品种',
                'verbose_name_plural': '交易品种',
                'db_table': 'market_instrument',
                'ordering': ['inst_id'],
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='最新价')),
                ('open_24h', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='24h开盘价')),
                ('high_24h', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='24h最高价')),
                ('low_24h', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='24h最低价')),
                ('vol_24h', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='24h成交量')),
                ('vol_ccy_24h', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='24h成交额')),
                ('bid_px', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='买一价')),
                ('bid_sz', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='买一量')),
                ('ask_px', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='卖一价')),
                ('ask_sz', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='卖一量')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='行情时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='market.instrument', verbose_name='交易品种')),
            ],
            options={
                'verbose_name': '行情快照',
                'verbose_name_plural': '行情快照',
                'db_table': 'market_ticker',
                'ordering': ['instrument__inst_id'],
            },
        ),
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(choices=[('1m', '1分钟'), ('3m', '3分钟'), ('5m', '5分钟'), ('15m', '15分钟'), ('30m', '30分钟'), ('1H', '1小时'), ('2H', '2小时'), ('4H', '4小时'), ('6H', '6小时'), ('12H', '12小时'), ('1D', '1天'), ('1W', '1周'), ('1M', '1月')], max_length=10, verbose_name='K线周期')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='K线时间')),
                ('open', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='收盘价')),
                ('vol', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='成交量')),
                ('vol_ccy', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='成交额(计价币)')),
                ('vol_ccy_quote', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='成交额(USD)')),
                ('confirm', models.IntegerField(default=0, verbose_name='K线状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='market.instrument', verbose_name='交易品种')),
            ],
            options={
                'verbose_name': 'K线数据',
                'verbose_name_plural': 'K线数据',
                'db_table': 'market_kline',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'bar', 'timestamp'], name='market_klin_instrum_04eebf_idx')],
                'unique_together': {('instrument', 'bar', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_rate', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='资金费率')),
                ('funding_time', models.DateTimeField(db_index=True, verbose_name='结算时间')),
                ('realized_rate', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='实际费率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rates', to='market.instrument', verbose_name='交易品种')),
            ],
            options={
                'verbose_name': '资金费率',
                'verbose_name_plural': '资金费率',
                'db_table': 'market_funding_rate',
                'unique_together': {('instrument', 'funding_time')},
            },
        ),
    ]
