# Generated by Django 6.0.4 on 2026-08-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_kline_environment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="kline",
            name="market_klin_instrum_04eebf_idx",
        ),
        migrations.RenameIndex(
            model_name="kline",
            new_name="market_klin_environ_99813f_idx",
            old_name="market_klin_environ_cd74b9_idx",
        ),
    ]
