# Generated by Django 4.2.30 on 2026-07-17 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=20, verbose_name='币种')),
                ('total_eq', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='总权益')),
                ('avail_eq', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='可用余额')),
                ('frozen_bal', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='冻结余额')),
                ('usd_value', models.DecimalField(decimal_places=4, max_digits=24, null=True, verbose_name='USD价值')),
                ('discount', models.DecimalField(decimal_places=4, default=1, max_digits=8, verbose_name='折算率')),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='快照时间')),
            ],
            options={
                'verbose_name': '余额快照',
                'verbose_name_plural': '余额快照',
                'db_table': 'account_balance_snapshot',
                'ordering': ['-snapshot_time', 'ccy'],
            },
        ),
        migrations.CreateModel(
            name='NetValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eq', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='总权益')),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='总盈亏')),
                ('daily_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='日盈亏')),
                ('pnl_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='收益率')),
                ('record_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '净值历史',
                'verbose_name_plural': '净值历史',
                'db_table': 'account_net_value',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(max_length=50, verbose_name='产品ID')),
                ('inst_type', models.CharField(max_length=20, verbose_name='产品类型')),
                ('pos_side', models.CharField(choices=[('long', '多头'), ('short', '空头')], max_length=10, verbose_name='持仓方向')),
                ('pos', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='持仓数量')),
                ('avg_px', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='开仓均价')),
                ('mark_px', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='标记价格')),
                ('liq_px', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='强平价')),
                ('upl', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='未实现盈亏')),
                ('margin', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='保证金')),
                ('mgn_ratio', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='保证金率')),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='杠杆倍数')),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='快照时间')),
            ],
            options={
                'verbose_name': '持仓快照',
                'verbose_name_plural': '持仓快照',
                'db_table': 'account_position_snapshot',
                'ordering': ['-snapshot_time'],
            },
        ),
    ]
