# Generated by Django 4.2.30 on 2026-07-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKXCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='名称')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=200, verbose_name='Secret Key')),
                ('passphrase', models.CharField(max_length=200, verbose_name='Passphrase')),
                ('flag', models.CharField(choices=[('0', '实盘 (Live)'), ('1', '模拟盘 (Demo)')], default='1', max_length=1, verbose_name='交易模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OKX凭证',
                'verbose_name_plural': 'OKX凭证',
                'db_table': 'account_okx_credential',
            },
        ),
    ]
