# Generated by Django 4.2.30 on 2026-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_okxcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_environment', models.CharField(choices=[('demo', '模拟盘'), ('live', '实盘')], default='demo', max_length=10, verbose_name='当前交易环境')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'account_system_config',
            },
        ),
        migrations.AlterField(
            model_name='okxcredential',
            name='name',
            field=models.CharField(choices=[('demo', '模拟盘'), ('live', '实盘')], default='demo', max_length=20, unique=True, verbose_name='环境'),
        ),
    ]
