# Generated by Django 4.2.30 on 2026-07-17 08:31

from django.db import migrations


def migrate_default_to_demo(apps, schema_editor):
    OKXCredential = apps.get_model('account', 'OKXCredential')
    SystemConfig = apps.get_model('account', 'SystemConfig')
    OKXCredential.objects.filter(name='default').update(name='demo')
    SystemConfig.objects.get_or_create(pk=1, defaults={'active_environment': 'demo'})


def reverse_migrate(apps, schema_editor):
    OKXCredential = apps.get_model('account', 'OKXCredential')
    OKXCredential.objects.filter(name='demo').update(name='default')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_systemconfig_alter_okxcredential_name'),
    ]

    operations = [
        migrations.RunPython(migrate_default_to_demo, reverse_migrate),
    ]

