# Generated by Django 6.0.8 on 2026-08-07 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_balancesnapshot_user_netvaluehistory_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('market_sync_interval', models.PositiveIntegerField(default=60, verbose_name='行情同步间隔(秒)')),
                ('market_sync_instruments', models.BooleanField(default=True, verbose_name='同步交易品种')),
                ('market_sync_tickers', models.BooleanField(default=True, verbose_name='同步行情快照')),
                ('market_sync_klines', models.BooleanField(default=True, verbose_name='同步K线数据')),
                ('max_tickers_sync_count', models.PositiveIntegerField(default=50, verbose_name='行情快照最大同步品种数')),
                ('global_max_position_pct', models.DecimalField(decimal_places=4, default=0.2, max_digits=5, verbose_name='全局最大持仓比例')),
                ('global_max_order_value', models.DecimalField(decimal_places=2, default=10000, max_digits=14, verbose_name='全局最大订单价值(USD)')),
                ('global_max_daily_loss', models.DecimalField(decimal_places=2, default=500, max_digits=14, verbose_name='全局最大日亏损(USD)')),
                ('global_stop_loss_pct', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='全局止损比例')),
                ('global_min_order_interval', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='全局最小下单间隔(秒)')),
                ('global_default_leverage', models.PositiveIntegerField(default=3, verbose_name='全局默认杠杆倍数')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='允许新用户注册')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'db_table': 'account_global_config',
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_strategies', models.PositiveIntegerField(default=10, verbose_name='最大策略数')),
                ('max_orders_per_day', models.PositiveIntegerField(default=100, verbose_name='每日最大下单次数')),
                ('max_api_calls_per_minute', models.PositiveIntegerField(default=60, verbose_name='每分钟最大API调用次数')),
                ('max_klines_per_request', models.PositiveIntegerField(default=500, verbose_name='单次K线查询上限')),
                ('is_trading_enabled', models.BooleanField(default=True, verbose_name='允许交易')),
                ('is_data_sync_enabled', models.BooleanField(default=True, verbose_name='允许数据同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户配额',
                'verbose_name_plural': '用户配额',
                'db_table': 'account_user_quota',
            },
        ),
    ]
