# Generated by Django 4.2.30 on 2026-07-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='因子名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('factor_type', models.CharField(choices=[('trend', '趋势类'), ('momentum', '动量类'), ('volatility', '波动类'), ('volume', '成交量类'), ('composite', '复合类')], max_length=20, verbose_name='因子类型')),
                ('description', models.TextField(blank=True, verbose_name='因子描述')),
                ('params', models.JSONField(default=dict, help_text='JSON格式的参数配置', verbose_name='因子参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '因子定义',
                'verbose_name_plural': '因子定义',
                'db_table': 'strategy_factor_definition',
            },
        ),
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('inst_type', models.CharField(default='SPOT', max_length=20, verbose_name='产品类型')),
                ('symbols', models.JSONField(default=list, help_text='例如: ["BTC-USDT", "ETH-USDT"]', verbose_name='交易标的列表')),
                ('bar', models.CharField(default='1H', max_length=10, verbose_name='K线周期')),
                ('direction', models.CharField(choices=[('long', '只做多'), ('short', '只做空'), ('both', '多空双向')], default='long', max_length=10, verbose_name='交易方向')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '已暂停'), ('stopped', '已停止')], default='draft', max_length=10, verbose_name='策略状态')),
                ('initial_capital', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='初始资金(USD)')),
                ('order_size_pct', models.DecimalField(decimal_places=4, default=0.1, help_text='0.1 = 每次使用可用资金的10%', max_digits=6, verbose_name='每次下单比例')),
                ('max_positions', models.IntegerField(default=5, verbose_name='最大持仓数')),
                ('stop_loss_pct', models.DecimalField(decimal_places=4, default=0.05, max_digits=6, verbose_name='止损比例')),
                ('take_profit_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=6, verbose_name='止盈比例')),
                ('factors', models.JSONField(default=list, help_text='例如: ["momentum", "volatility", "rsi", "macd"]', verbose_name='使用因子列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '策略配置',
                'verbose_name_plural': '策略配置',
                'db_table': 'strategy_config',
            },
        ),
        migrations.CreateModel(
            name='SignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(max_length=50, verbose_name='交易标的')),
                ('signal', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('close_long', '平多'), ('close_short', '平空'), ('hold', '持有')], max_length=20, verbose_name='信号类型')),
                ('score', models.DecimalField(decimal_places=4, default=0, help_text='综合因子量化评分, 0~1', max_digits=8, verbose_name='信号评分')),
                ('factors_detail', models.JSONField(default=dict, help_text='{"momentum": 0.8, "rsi": 0.3}', verbose_name='各因子详情')),
                ('price', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='当前价格')),
                ('reason', models.TextField(blank=True, verbose_name='信号原因')),
                ('is_executed', models.BooleanField(default=False, verbose_name='是否已执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='信号时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategy.strategyconfig', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '交易信号',
                'verbose_name_plural': '交易信号',
                'db_table': 'strategy_signal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='回测开始')),
                ('end_date', models.DateTimeField(verbose_name='回测结束')),
                ('initial_capital', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='初始资金')),
                ('final_capital', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='最终资金')),
                ('total_return', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='总收益率')),
                ('annual_return', models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='年化收益率')),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='夏普比率')),
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='最大回撤率')),
                ('win_rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='胜率')),
                ('total_trades', models.IntegerField(verbose_name='总交易次数')),
                ('profit_trades', models.IntegerField(verbose_name='盈利交易')),
                ('loss_trades', models.IntegerField(verbose_name='亏损交易')),
                ('avg_profit', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='平均盈利')),
                ('avg_loss', models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='平均亏损')),
                ('profit_factor', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='盈亏比')),
                ('equity_curve', models.JSONField(default=list, verbose_name='权益曲线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategy.strategyconfig', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '回测结果',
                'verbose_name_plural': '回测结果',
                'db_table': 'strategy_backtest',
                'ordering': ['-created_at'],
            },
        ),
    ]
