# Generated by Django 4.2.30 on 2026-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrecord',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='杠杆倍数'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='pos_side',
            field=models.CharField(blank=True, choices=[('long', '多头'), ('short', '空头'), ('net', '净仓')], max_length=10, verbose_name='持仓方向'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='td_mode',
            field=models.CharField(blank=True, max_length=10, verbose_name='保证金模式'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=3, help_text='例如 3 = 3x 杠杆', max_digits=6, verbose_name='杠杆倍数'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='strategy_type',
            field=models.CharField(choices=[('factor_composite', '因子综合评分'), ('trend_follow', '趋势跟踪')], default='factor_composite', max_length=30, verbose_name='策略类型'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='td_mode',
            field=models.CharField(choices=[('cash', '现金/现货'), ('cross', '全仓合约'), ('isolated', '逐仓合约')], default='cross', help_text='合约交易使用 cross 全仓或 isolated 逐仓', max_length=10, verbose_name='保证金模式'),
        ),
        migrations.AlterField(
            model_name='signalrecord',
            name='signal',
            field=models.CharField(choices=[('buy', '买入/开多'), ('sell', '卖出/开空'), ('close_long', '平多'), ('close_short', '平空'), ('hold', '持有')], max_length=20, verbose_name='信号类型'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='inst_type',
            field=models.CharField(default='SWAP', max_length=20, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='order_size_pct',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='0.1 = 每次使用保证金的10%', max_digits=6, verbose_name='每次下单比例'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='symbols',
            field=models.JSONField(default=list, help_text='例如: ["BTC-USDT-SWAP", "ETH-USDT-SWAP"]', verbose_name='交易标的列表'),
        ),
    ]
