# Generated by Django 4.2.30 on 2026-08-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_signalrecord_leverage_signalrecord_pos_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrecord',
            name='entry_atr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='入场ATR'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='止损价'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='止盈价'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='tp_mode',
            field=models.CharField(blank=True, help_text='fixed=固定盈亏比, trailing=移动止盈', max_length=20, verbose_name='止盈模式'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON格式的策略专属参数，例如放量跟随的 VOL_RATIO 等', verbose_name='策略参数'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='strategy_type',
            field=models.CharField(choices=[('factor_composite', '因子综合评分'), ('trend_follow', '趋势跟踪'), ('volume_breakout', '放量跟随')], default='factor_composite', max_length=30, verbose_name='策略类型'),
        ),
        migrations.CreateModel(
            name='TrackedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(max_length=50, verbose_name='交易标的')),
                ('side', models.CharField(choices=[('long', '多头'), ('short', '空头')], max_length=10, verbose_name='持仓方向')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='入场价')),
                ('entry_atr', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='入场ATR')),
                ('stop_loss_price', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='止损价')),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='止盈价')),
                ('tp_mode', models.CharField(choices=[('fixed', '固定盈亏比'), ('trailing', '移动止盈')], default='fixed', max_length=20, verbose_name='止盈模式')),
                ('highest_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='持仓期间最高价')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='持仓期间最低价')),
                ('trailing_active', models.BooleanField(default=False, verbose_name='移动止盈已激活')),
                ('trailing_stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='移动止损价')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否持仓中')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='开仓时间')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='平仓时间')),
                ('exit_reason', models.CharField(blank=True, max_length=50, verbose_name='平仓原因')),
                ('daily_stop_count', models.IntegerField(default=0, verbose_name='当日止损笔数')),
                ('daily_stop_date', models.DateField(blank=True, null=True, verbose_name='止损统计日期')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='strategy.strategyconfig', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '策略持仓跟踪',
                'verbose_name_plural': '策略持仓跟踪',
                'db_table': 'strategy_tracked_position',
                'unique_together': {('strategy', 'inst_id')},
            },
        ),
    ]
