# Generated by Django 6.0.4 on 2026-08-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategy",
            "0003_signalrecord_entry_atr_signalrecord_stop_loss_price_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factordefinition",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factor_definitions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="factordefinition",
            name="name",
            field=models.CharField(max_length=50, verbose_name="因子名称"),
        ),
        migrations.AlterField(
            model_name="strategyconfig",
            name="name",
            field=models.CharField(max_length=100, verbose_name="策略名称"),
        ),
        migrations.AlterUniqueTogether(
            name="factordefinition",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="strategyconfig",
            unique_together={("user", "name")},
        ),
    ]
