# Generated by Django 4.2.30 on 2026-08-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_factordefinition_user_strategyconfig_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordefinition',
            name='formula',
            field=models.TextField(blank=True, help_text='自定义因子 pandas 表达式，如 close/close.rolling(20).mean()-1。方向: 值越大越看多', verbose_name='计算公式'),
        ),
        migrations.AddField(
            model_name='factordefinition',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否自定义'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='factor_weights',
            field=models.JSONField(blank=True, default=dict, help_text='因子权重映射，如 {"momentum": 0.3, "rsi": 0.2}；留空则等权', verbose_name='因子权重'),
        ),
        migrations.CreateModel(
            name='StrategyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组合名称')),
                ('description', models.TextField(blank=True, verbose_name='组合描述')),
                ('strategies', models.JSONField(default=list, help_text='[{"strategy_id": 1, "weight": 0.5}]', verbose_name='组合策略及权重')),
                ('initial_capital', models.DecimalField(decimal_places=4, default=1000, max_digits=20, verbose_name='初始资金(USD)')),
                ('status', models.CharField(choices=[('active', '运行中'), ('paused', '已暂停'), ('stopped', '已停止')], default='stopped', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '策略组合',
                'verbose_name_plural': '策略组合',
                'db_table': 'strategy_portfolio',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
