# Generated by Django 4.2.30 on 2026-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_factordefinition_formula_factordefinition_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='fee_rate',
            field=models.DecimalField(decimal_places=6, default=0.001, max_digits=8, verbose_name='手续费率'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='is_optimized',
            field=models.BooleanField(default=False, verbose_name='是否优化结果'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='monte_carlo',
            field=models.JSONField(blank=True, default=dict, verbose_name='蒙特卡洛模拟'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='slippage',
            field=models.DecimalField(decimal_places=6, default=0.001, max_digits=8, verbose_name='滑点(百分比)'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='trade_detail',
            field=models.JSONField(default=list, verbose_name='交易明细'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='walk_forward',
            field=models.JSONField(blank=True, default=dict, verbose_name='Walk-forward分析'),
        ),
    ]
