# Generated by Django 4.2.30 on 2026-08-08 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_state', '订单状态更新'), ('signal_generated', '策略信号'), ('risk_warning', '风控告警'), ('strategy_event', '策略事件'), ('backtest_done', '回测完成'), ('system_notice', '系统公告'), ('market_alert', '行情异动')], default='system_notice', max_length=32)),
                ('level', models.IntegerField(choices=[(10, 'info'), (20, 'success'), (30, 'warning'), (40, 'danger')], default=10)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, default='')),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('target_route', models.CharField(blank=True, default='', help_text='如 /orders?tab=normal / /strategy/signals?id=123', max_length=200)),
                ('related_model', models.CharField(blank=True, default='', help_text='如 TradeOrder / SignalRecord / BacktestResult', max_length=64)),
                ('related_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='空=全局/单用户模式下所有用户可见', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
    ]
